#:kivy 1.8.0
#:import KivyLexer kivy.extras.highlight.KivyLexer
#:import Factory kivy.factory.Factory


# <SpecialLabel@Label>

#   # text:'123'

# <SpeciaButton@Button>
#   # controlled_label:spec_lab

#   text: 'spec b'

# VERSION_RELEASE_NUMBER= '0.8'
<Button>:
    font_size: dp(18)
    # font_name: 'Futura.ttc'


<Label>:
    # font_size: dp(20)
    # font_name: 'Jost/static/Jost-Regular.ttf'
    font_name: 'Jost'
    # font_name: 'Jost/static/Jost-Medium.ttf'
    # font_name: 'Futura.ttc'


<EmptySpace@Label>
    # text: 'empty'


# <ToggleButton>:
    # canvas.before:
    #     Color:
    #         rgba: (0.329, 0.635, 0.792, 1) if self.disabled else (1, 0.345, 0.345, 1)  # Disabled background color
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size
    # background_normal: ''
    # background_color: 0, 1, 0, 1
    # disabled_color: (1,1,1, 1)

# H2_FONT_SIZE: dp(30)

# <KeyView@Button>
#     text: 'KeyView'

# <KeyViewRootAndDescription@BoxLayout>

#     key_view_root: key_view_root
#     key_view_description: key_view_description
#     root_slider: root_slider
#     orientation: 'vertical'
#     spacing: 10
#     Button:
#         text: 'A'
#         size_hint_y: 4
#         id: key_view_root
#         font_size: '100sp'
#     BoxLayout:
#         size_hint_y: 0.8
#         orientation: 'horizontal'
#         EmptySpace:
#             size_hint_x: 0.2
#         Slider:
#             id: root_slider
#             value_track: True,
#             value_track_color: (1,0,0,1)
#             min: 0
#             max: 11
#             step: 1
#         EmptySpace:
#             size_hint_x: 0.2
#     BoxLayout:
#         # minimum_height: 400
#         Button:
#             id: key_view_description
#             text: 'A Minor'
#             background_color: (.2, 1, 1, 1)
#             font_size: '10dp'

# <KeyView@BoxLayout>
#     key_view_root_and_destination: key_view_root_and_destination
#     text: 'KeyView'
#     orientation: 'vertical'
#     EmptySpace:
#     KeyViewRootAndDescription:
#         id: key_view_root_and_destination
#         size_hint_y:4
#     EmptySpace:


# <NoteSpinnerSliderComboSpinner@Spinner>



<NoteSpinnerSliderCombo@BoxLayout>
    note_spinner: note_spinner
    note_slider: note_slider

    text: 'default'

    orientation: 'vertical'

    size_hint_x: None
    width: self.note_spinner.height


    NoteSpinnerSliderComboSpinner:
        canvas.after:

            # Color:
            #     rgba: (0.89, 0.09, 0.584, .5)  # Red
            #     # rgba: (.9, .9, .9, .6)
            # Rectangle:
            #     pos: self.pos
            #     size: self.size
            #     # pos: (self.center_x - min(self.width, self.height)/2, self.y)
            #     # size: (min(self.width, self.height), min(self.width, self.height))
            #     # size: (self.width, self.height)
            #     group: 'auto_root_color'


            # Color:
            #     rgba: (.9, .9, .9, .6)
            # Ellipse:
            #     pos: (self.center_x - min(self.width, self.height)/2, self.y)
            #     size: (min(self.width, self.height), min(self.width, self.height))
                # size: (self.width, self.height)


        size_hint_y: 1
        size: (min(self.width, self.height), min(self.width, self.height))
        # size_hint: None, None
        # size: 100, 44
        # pos_hint: {'center': (.5, .5)}
        id: note_spinner
        text: root.text
        # auto_root_color: False
        font_size: dp(63)
        values: 'none'

        # Label:
        #     size_hint_y: 1
        #     size: (min(self.width, self.height), min(self.width, self.height))
        #     # size_hint: None, None
        #     # size: 100, 44
        #     # pos_hint: {'center': (.5, .5)}
        #     # id: note_spinner
        #     text: root.text
        #     font_size: dp(63)
        #     values: 'none'

        # on_text:
        #     print("The spinner {} has text {}".format(self, self.text))
        # size_hint_y: 1
    # EmptySpace:
    #     size_hint_y: 0.1


    Slider:
        id: note_slider
        value_track: True,
        value_track_color: (1,0,0,0)
        # value_track_color: (1,0,0,1)
        min: 0
        max: 11
        step: 1
        size_hint_y: 0.25




# For Fitted Selection.  with close_button
<GridNote@BoxLayout>
    close_button: close_button
    main_button: main_button
    top_bar: top_bar
    close_button_box: close_button_box
    top_bar_close_box: top_bar_close_box
    top_bar_label: top_bar_label

    text: 'default'
    orientation: 'vertical'
    size_hint_x: None
    size_hint_y: None

    # width: self.main_button.height
    height: self.main_button.width * 1.3

    # size_hint_y: None
    # height: dp(35)
    # size_hint_x: 1
    # size_hint_y: 1

    is_root: False

    # background_normal: ''
    # background_color: 0.506, 0.173, 0.859, 1

    BoxLayout:
        id: top_bar
        orientation: 'horizontal'
        # padding: [0, 0, dp(8), 0]
        size_hint_y: .3
        spacing: 0
        Button:
            id: top_bar_label
            padding: [0,0,0,5]
            # size_hint_x: 1
            text: ''
            font_size: dp(11)
            # background_color: (0,0,0,0)
        BoxLayout:
            orientation: 'horizontal'
            id: top_bar_close_box
            size_hint_x: .7
            spacing: 0
            # Button:
            #     size_hint_x: .5
            #     text: ''
            #     font_size: dp(11)
                # background_color: (0,0,0,0)
            BoxLayout:
                id: close_button_box
                size_hint_x: 1
                Button:
                    id: close_button
                    text: 'X'
                    font_size: dp(11)
                    on_press:
                        print('>close_button')
                        print(self)
                        print(root)

    # normal_button_background_color: Color(0.345, 0.345, 0.345, 1)
    Button:
        canvas.after:
            Color:
                rgba: (.9, .9, .9, .6) if root.is_root else (0, 0, 0, 0)
            Ellipse:
                # pos: (self.center_x - min(self.width, self.height)/2, self.y)
                pos: (main_button.center_x - min(main_button.width, main_button.height)/2, main_button.y)
                # size: (min(self.width, self.height), min(self.width, self.height))
                # size: (self.width, self.height)
                size: (main_button.width, main_button.height)
        id: main_button
        text: root.text
        font_size: dp(27)
        background_normal: ''
        background_color: 0.506, 0.173, 0.859, 1
        background_down: ''
        # background_down: 'background/input_denied.png'
        on_press: self.background_color = (1.0, 0.0, 0.0, 1.0)


<FittedScaleToggle@BoxLayout>
    select_scale_button: select_scale_button
    # favorite_button: favorite_button
    # lock_button: lock_button

    text: 'default scale'
    state: 'normal'
    select_scale_button: select_scale_button
    fs_font_size: dp(10)

    size_hint_y: None
    height: dp(35)
    # size_hint_y: 5

    ToggleButton:
        id: select_scale_button
        text: root.text
        font_size: root.fs_font_size
        size_hint_x: 8
        state: root.state
        markup: True
        group: 'fitted_scale_toggle'
    # ToggleButton:
    #     id: favorite_button
    #     text: 'F'
    #     font_size: dp(12)
    # ToggleButton:
    #     id: lock_button
    #     text: 'L'
    #     font_size: dp(12)




<ScaleSelectorView@BoxLayout>
    # text: 'ScaleSelectorView'

    screen_manager_selector_view: screen_manager_selector_view


    by_definition_tab_toggle: by_definition_tab_toggle
    by_note_tab_toggle: by_note_tab_toggle
    root_spinner_slider_combo: root_spinner_slider_combo

    root_increment_down_id: root_increment_down_id
    root_increment_up_id: root_increment_up_id

    root_spinner_slider_combo_2: root_spinner_slider_combo_2
    screen_manager_selector_view: screen_manager_selector_view

    root_label_id: root_label_id
    selected_label_id: selected_label_id

    scale_by_defition_screen_id: scale_by_defition_screen_id
    scale_by_note_screen_id: scale_by_note_screen_id

    root_option_description_label: root_option_description_label
    manual_root_selection_button: manual_root_selection_button
    # for_each_root_selection_button: for_each_root_selection_button
    auto_root_selection_button: auto_root_selection_button
    clear_selected_button: clear_selected_button
    fragment_notes_grid: fragment_notes_grid
    fitted_scale_toggle_grid: fitted_scale_toggle_grid
    # fitted_scale_toggle_slider: fitted_scale_toggle_slider
    # fitted_scale_toggle_slider: 0

    fitted_scales_label_box_id: fitted_scales_label_box_id
    fitted_scales_label_id: fitted_scales_label_id
    fitted_sales_increment_choice_up_button_id: fitted_sales_increment_choice_up_button_id
    fitted_sales_increment_choice_down_button_id: fitted_sales_increment_choice_down_button_id
    fitted_sales_increment_page_button_id: fitted_sales_increment_page_button_id
    fitted_sales_increment_page_button_id_2: fitted_sales_increment_page_button_id_2

    # root_spinner: root_spinner
    # root_slider: root_slider

    # root_spinner_slider_combo

    scale_type_spinner: scale_type_spinner
    scale_type_label_id: scale_type_label_id
    mode_name_spinner: mode_name_spinner
    mode_name_label_id: mode_name_label_id
    scale_logo_id: scale_logo_id
    scale_logo_1_id: scale_logo_1_id
    scale_logo_2_id: scale_logo_2_id

    new_feature_label_id: new_feature_label_id
    circle_of_fifths_box_id: circle_of_fifths_box_id
    yinyang_logo_id: yinyang_logo_id

    scale_type_chev_up_button_id: scale_type_chev_up_button_id
    scale_type_chev_down_button_id: scale_type_chev_down_button_id
    mode_name_chev_up_button_id: mode_name_chev_up_button_id
    mode_name_chev_down_button_id: mode_name_chev_down_button_id


    by_definition_tab_toggle: by_definition_tab_toggle
    by_note_tab_toggle: by_note_tab_toggle

    select_scale_by_tabs: select_scale_by_tabs


    orientation: 'vertical'
    # BoxLayout:
    #     orientation: 'vertical'
    #     EmptySpace:
    #         text: 'asdfasdf'
    #         size_hint_x: 10


    # BoxLayout:

    h2_font_size: dp(26)
    h3_font_size: dp(19)
    h4_font_size: dp(9)

    line_width: 2

    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            id: select_scale_by_tabs
            canvas.before:
                Color:
                    # rgba: 1,1,1, 1
                    rgba: 0.4,0.4,0.4, 1
                Line:
                    width: root.line_width
                    points: select_scale_by_tabs.x, select_scale_by_tabs.y, select_scale_by_tabs.x + select_scale_by_tabs.width, select_scale_by_tabs.y

            spacing: dp(1)
            size_hint_y: 0.1
            # Label:
            #     text: '-'
            #     size_hint_x: .01
            #     font_size: dp(19)

            BoxLayout:
                # Label:
                #     text: 'Select Scale'
                #     font_size: dp(25)
                #     size_hint_x: .8
                #     halign: 'left'
                #     text_size: self.size

                ToggleButton:
                    text: 'Select Scale by Note'
                    # text: 'By Note'
                    id: by_note_tab_toggle
                    group: 'scale_selection_tab_toggle'
                    font_size: dp(19)
                    size_hint_x: .4
                    state: 'down'

                ToggleButton:
                    text: 'Select Scale by Definition'
                    # text: 'By Definition'
                    id: by_definition_tab_toggle
                    group: 'scale_selection_tab_toggle'
                    font_size: dp(19)
                    size_hint_x: .5
                    # size_hint_x: 1
            EmptySpace:
                size_hint_x: .5


        BoxLayout:
            padding: [0, dp(7), 0, dp(0)]

            # padding: dp(20)
            # # Border
            # canvas.before:
            #     Color:
            #         rgba: 1, 1,1, .5
            #     Line:
            #         width: 2
            #         rectangle: self.x, self.y, self.width, self.height

            ScreenManager:
                id: screen_manager_selector_view


                Screen:
                    name: 'scale_by_defition_screen'
                    id: scale_by_defition_screen_id

                    BoxLayout:
                        orientation: 'horizontal'

                        spacing: dp(15)

                        BoxLayout:
                            orientation: 'vertical'

                            # Root selection and options row
                            BoxLayout:
                                orientation: 'vertical'
                                size_hint_y: 1.8 # <<< Top level

                                # Root label and info column
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_y: .25
                                    Label:
                                        text: 'Root:'
                                        halign: 'left'
                                        id: root_label_id
                                        text_size: self.size
                                        font_size: root.h2_font_size



                                    # # Root entry toggle modes column
                                    # BoxLayout:
                                    #     orientation: 'vertical'
                                    #     # spacing: 5
                                    #     padding: [80, 0, 80, 0]

                                    #     BoxLayout:
                                    #         size_hint_y: 1
                                    #         orientation: 'vertical'
                                    #         ToggleButton:
                                    #             text: 'Manual Root'
                                    #             id: manual_root_selection_button
                                    #             size_hint_y: 1
                                    #             font_size: dp(15)
                                    #             state: 'down'
                                    #             group: 'root_option_group'
                                    #         ToggleButton:
                                    #             text: 'For each'
                                    #             id: for_each_root_selection_button
                                    #             size_hint_y: 1
                                    #             font_size: dp(15)
                                    #             group: 'root_option_group'

                                    #         ToggleButton:
                                    #             text: 'Auto-Root'
                                    #             id: auto_root_selection_button
                                    #             size_hint_y: 1
                                    #             font_size: dp(15)
                                    #             group: 'root_option_group'

                                        # BoxLayout:
                                        #     orientation: 'vertical'
                                        #     size_hint_y: 0.25
                                        #     EmptySpace:
                                        #         text: '-'
                                        #         size_hint_y: 1


                                    Label:
                                        text: ''
                                        id: root_option_description_label
                                        font_size: '9dp'
                                        size_hint_y: 1



                                # Root selection column


                                # Root Selector
                                BoxLayout:
                                    orientation: 'horizontal'
                                    BoxLayout:
                                        orientation: 'vertical'
                                        Button:
                                            text: '\u25C2'
                                            id: root_increment_down_id
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                            font_name: 'build_fonts/Arial Unicode.ttf'
                                            background_color: [0,0,0,1]
                                            color: [.3,.3,.3,1]
                                        EmptySpace:
                                            size_hint_y: 0.25

                                    # Root Selector
                                    NoteSpinnerSliderCombo:
                                        id: root_spinner_slider_combo
                                        # size_hint_x: 4
                                    BoxLayout:
                                        orientation: 'vertical'
                                        Button:
                                            text: '\u25B8'
                                            id: root_increment_up_id
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                            font_name: 'build_fonts/Arial Unicode.ttf'
                                            background_color: [0,0,0,1]
                                            color: [.3,.3,.3,1]
                                        EmptySpace:
                                            size_hint_y: 0.25

                                # Root entry toggle modes column
                                BoxLayout:
                                    orientation: 'vertical'
                                    # spacing: 5
                                    # padding: [5, 0, 0, 0]
                                    size_hint_y: .2

                                    BoxLayout:
                                        # size_hint_y: .3
                                        orientation: 'horizontal'
                                        padding: [dp(75),0,dp(75),0]
                                        ToggleButton:
                                            text: 'Manual Root'
                                            id: manual_root_selection_button
                                            # size_hint_y: 1
                                            size_hint_x: 1
                                            font_size: dp(15)
                                            group: 'root_option_group'
                                        # ToggleButton:
                                        #     text: 'For each'
                                        #     # id: for_each_root_selection_button
                                        #     # size_hint_y: 1
                                        #     size_hint_x: 1
                                        #     font_size: dp(15)
                                        #     group: 'root_option_group'

                                        ToggleButton:
                                            background_down: 'background/auto_root.png'
                                            text: 'Auto-Root'
                                            id: auto_root_selection_button
                                            # size_hint_y: 1
                                            size_hint_x: 1
                                            font_size: dp(15)
                                            group: 'root_option_group'
                                            state: 'down'

                                    # BoxLayout:
                                    #     orientation: 'vertical'
                                    #     size_hint_y: 0.1
                                    #     EmptySpace:
                                    #         text: '-'
                                    #         size_hint_y: 1



                            # EmptySpace:
                            #     size_hint_y: 0.1

                            # Scale Fragment notes row
                            BoxLayout:
                                orientation: 'vertical'
                                size_hint_y: .4
                                # spacing: 10
                                padding: [0, 15, 0, 0]

                                BoxLayout:
                                    orientation: 'vertical'
                                    # size_hint_x: .4
                                    spacing: dp(5)
                                    Label:
                                        text: 'Selected:'
                                        halign: 'left'
                                        id: selected_label_id
                                        text_size: self.size

                                        # font_size: dp(25)
                                        font_size: root.h2_font_size
                                        size_hint_y: 1

                            BoxLayout:
                                orientation: 'horizontal'
                                size_hint_x: 1
                                BoxLayout:
                                    orientation: 'horizontal'

                                    size_hint_x: .4
                                    Label:
                                        size_hint_x: .5
                                    BoxLayout:
                                        orientation: 'vertical'
                                        size_hint_x: 2
                                        EmptySpace:
                                            size_hint_y: .3
                                        Button:
                                            text: 'Clear'
                                            id: clear_selected_button
                                            font_size: root.h3_font_size
                                        EmptySpace:
                                            size_hint_y: 1

                                        # size_hint_y: 1.8
                                    Label:
                                        size_hint_x: .5


                                # Current fragment selection
                                GridLayout:
                                    id: fragment_notes_grid
                                    # minimum_rows:3
                                    # minimum_cols: 5
                                    padding: [0,dp(5),0, 0]

                                    cols: 6
                                    rows: 2
                                    # orientation: 'horizontal'
                                    spacing:dp(5)
                                    # GridNote:
                                    #     text: 'B'
                                # Button:






                        # Fitted scales row
                        BoxLayout:
                            orientation: 'vertical'


                            # Fitted scales row
                            BoxLayout:
                                orientation: 'vertical'
                                size_hint_y: 1.8


                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_y: 1.7

                                    id: fitted_scales_label_box_id
                                    # Border
                                    canvas.before:
                                        Color:
                                            # rgba: 1,1,1, 1
                                            rgba: 0.4,0.4,0.4, 1
                                        Line:
                                            width: root.line_width
                                            points: fitted_scales_label_box_id.x, fitted_scales_label_box_id.y, fitted_scales_label_box_id.x + fitted_scales_label_box_id.width, fitted_scales_label_box_id.y

                                    Label:
                                        text: 'Fitted Scales:'
                                        id: fitted_scales_label_id
                                        size_hint_x: 5
                                        halign: 'left'
                                        padding: [dp(0),dp(0),dp(0),dp(3)]
                                        text_size: self.size

                                        font_size: root.h2_font_size
                                    BoxLayout:
                                        orientation: 'vertical'
                                        size_hint_x: 3

                                        EmptySpace:
                                            size_hint_y: 1
                                        BoxLayout:
                                            orientation: 'horizontal'
                                            size_hint_y: 3


                                            padding: [dp(10),dp(0),dp(0),dp(10)]

                                            Button:
                                                # Border
                                                canvas.before:
                                                    Color:
                                                        rgb: 0.4,0.4,0.4
                                                    Line:
                                                        width: root.line_width
                                                        rectangle: self.x, self.y, self.width, self.height
                                                text: '\u25C2'
                                                id: fitted_sales_increment_choice_down_button_id
                                                size_hint_x: 1
                                                # text_size: self.size
                                                # halign: 'right'
                                                # valign: 'middle'
                                                font_name: 'build_fonts/Arial Unicode.ttf'
                                                # background_color: [0,0,0,1]
                                                # color: [.3,.3,.3,1]
                                                background_down: ''
                                                background_color: [0,0,0]
                                                color: [.6,.6,.6]



                                            Button:
                                                # Border
                                                canvas.before:
                                                    Color:
                                                        rgb: 0.4,0.4,0.4
                                                    Line:
                                                        width: root.line_width
                                                        rectangle: self.x, self.y, self.width, self.height
                                                text: '\u25B8'
                                                id: fitted_sales_increment_choice_up_button_id
                                                size_hint_x: 1
                                                # text_size: self.size
                                                # halign: 'left'
                                                # valign: 'middle'
                                                font_name: 'build_fonts/Arial Unicode.ttf'
                                                # background_color: [0,0,0,1]
                                                # color: [.3,.3,.3,1]
                                                background_down: ''
                                                background_color: [0,0,0]
                                                color: [.6,.6,.6]

                                            EmptySpace:
                                                size_hint_x: 0.2

                                            Button:
                                                # Border
                                                canvas.before:
                                                    Color:
                                                        rgb: 0.4,0.4,0.4
                                                    Line:
                                                        width: root.line_width
                                                        rectangle: self.x, self.y, self.width, self.height

                                                text: '\u25BC'
                                                id: fitted_sales_increment_page_button_id
                                                size_hint_x: 1.5
                                                # padding: [dp(10),0,0,]
                                                # text_size: self.size
                                                # halign: 'left'
                                                # valign: 'middle'
                                                font_name: 'build_fonts/Arial Unicode.ttf'
                                                # background_color: [0,0,0,1]
                                                # color: [.3,.3,.3,1]
                                                background_down: ''
                                                background_color: [0,0,0]
                                                color: [.6,.6,.6]


                                            EmptySpace:
                                                size_hint_x: 0.2





                                # List of all matching scales result grid
                                BoxLayout: # Just in case
                                    orientation: 'horizontal'
                                    size_hint_y: 12
                                    padding: [0, dp(10), 0, dp(10)]
                                    GridLayout:
                                        id: fitted_scale_toggle_grid
                                        cols: 2
                                        rows: 8
                                        spacing: dp(8)
                                        # padding: 4
                                        FittedScaleToggle:
                                            text: 'B harmonic minor'
                                        FittedScaleToggle:
                                            text: 'B Lydian'
                                        FittedScaleToggle:
                                            text: 'B Diminished (W-H)'
                                        FittedScaleToggle:
                                            text: 'B Diminished (W-H)'

                                        FittedScaleToggle:
                                            text: 'B Diminished (W-H)'

                                        FittedScaleToggle:
                                            text: 'B Diminished (W-H)'

                                        # FittedScaleToggle:
                                        #     text: 'B Diminished (W-H)'

                                        # EmptySpace:
                                        #     text: 'B Diminished (W-H)'


                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_y: 1
                                    padding: [dp(1),dp(1),dp(2),dp(1)]

                                    EmptySpace:
                                        size_hint_x: 1


                                    Button:
                                        # Border
                                        canvas.before:
                                            Color:
                                                rgb: 0.4,0.4,0.4
                                            Line:
                                                width: root.line_width
                                                rectangle: self.x, self.y, self.width, self.height

                                        text: '\u25BC'
                                        id: fitted_sales_increment_page_button_id_2
                                        size_hint_x: 5
                                        # size_hint_x: 1.5
                                        text_size: self.size
                                        halign: 'center'
                                        valign: 'middle'
                                        font_name: 'build_fonts/Arial Unicode.ttf'
                                        # background_color: [0,0,0,1]
                                        # color: [.3,.3,.3,1]

                                        background_normal: ''
                                        background_color: (0, 0, 0, 0)  # RGBA for black (full opacity)

                                        # background_color: [0,0,0, 0]
                                        # background_down: 'background/input_denied.png'
                                        background_down: ''
                                        color: [.6,.6,.6]

                                    EmptySpace:
                                        size_hint_x: 1

                                    # Slider:
                                    #     id: fitted_scale_toggle_slider
                                    #     orientation: 'vertical'
                                    #     size_hint_x: 0.1
                                    #     # padding: 60
                                    #     # value_track: True,
                                    #     value_track_color: (1,0,0,0)
                                    #     min: 0
                                    #     max: 30
                                    #     # step: .5
                                    #     # size_hint_y: 0.



                                # # Extra options Row
                                # BoxLayout:
                                #     orientation: 'horizontal'
                                #     size_hint_y: 0.3
                                    # padding: 5

                                    # Button:
                                    #     text: '-'
                                    #     size_hint_x: 0.5




                    # BoxLayout:
                    #     orientation: 'vertical'

                    # BoxLayout:
                    #     orientation: 'vertical'

                    # BoxLayout:
                    #     orientation: 'vertical'


                    #     EmptySpace:
                    #         text: 'stuff'
                    #     EmptySpace:
                    #         text: 'stuff2'
                    #     EmptySpace:
                    #         text: 'stuff3'

                Screen:
                    name: 'scale_by_note_screen'
                    id: scale_by_note_screen_id

                    BoxLayout:
                        orientation: 'horizontal'

                        BoxLayout:
                            orientation: 'vertical'
                            # size_hint_y: 2
                            # BoxLayout:
                            #     size_hint_y: .2
                            #     EmptySpace:
                            #     Button:
                            #         text: "options"
                            #     EmptySpace:

                            padding: [0, dp(40), 0, 0]

                            BoxLayout:
                                orientation: 'vertical'
                                spacing: dp(3)
                                size_hint_y: 10
                                BoxLayout:
                                    orientation: 'horizontal'

                                    size_hint_y: 1.5
                                    padding: [dp(0),dp(0),dp(0),dp(10)]

                                    # EmptySpace:
                                    ScaleInfo:
                                        id: scale_logo_1_id
                                        # size_hint_y: 2
                                        color: [0.7,0.7,0.7,1]

                                    # Root Selector
                                    NoteSpinnerSliderCombo:
                                        id: root_spinner_slider_combo_2
                                        # size_hint_x: 4

                                    # EmptySpace:
                                    ScaleInfo:
                                        id: scale_logo_2_id
                                        color: [0.7,0.7,0.7,1]
                                        # size_hint_y: 2

                                # Spinner:
                                #     # size_hint: None, None
                                #     # size: 100, 44
                                #     # pos_hint: {'center': (.5, .5)}
                                #     id: root_spinner
                                #     text: 'Home'
                                #     font_size: dp(28)
                                #     values: 'Home', 'Work', 'Other', 'Custom'
                                #     on_text:
                                #         print("The spinner {} has text {}".format(self, self.text))
                                #     size_hint_y: 1.2

                                # Slider:
                                #     id: root_slider
                                #     value_track: True,
                                #     value_track_color: (1,0,0,1)
                                #     min: 0
                                #     max: 11
                                #     step: 1
                                #     size_hint_y: 0.3

                                # EmptySpace:
                                #     size_hint_y: 0.2

                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_y: 0.3
                                    padding: [0,dp(5), dp(20), dp(0)]
                                    spacing: dp(1)
                                    Label:
                                        text: 'Scale Type: '
                                        id: scale_type_label_id
                                        size_hint_x: 0.5
                                        halign: 'right'
                                        text_size: self.size
                                        valign: 'middle'

                                    Spinner:
                                        # size_hint: None, None
                                        # size: 50, 44
                                        # pos_hint: {'center': (.5, .5)}
                                        id: scale_type_spinner
                                        text: 'Home'
                                        values: 'Home', 'Work', 'Other', 'Custom'
                                    BoxLayout:
                                        orientation: 'vertical'
                                        size_hint_x: 0.2
                                        spacing: dp(1)
                                        Button:
                                            text: '\u25B2'
                                            id: scale_type_chev_up_button_id
                                            font_name: 'build_fonts/Arial Unicode.ttf'
                                        Button:
                                            text: '\u25BC'
                                            id: scale_type_chev_down_button_id
                                            font_name: 'build_fonts/Arial Unicode.ttf'

                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_y: 0.3
                                    spacing:dp(1)
                                    padding: [0,dp(5), dp(20), dp(0)]
                                    Label:
                                        text: 'Scale Mode: '
                                        id: mode_name_label_id
                                        size_hint_x: 0.5
                                        halign: 'right'
                                        text_size: self.size
                                        valign: 'middle'

                                    Spinner:
                                        # size_hint: None, None
                                        # size: 100, 44
                                        # pos_hint: {'center': (.5, .5)}
                                        id: mode_name_spinner
                                        text: 'Home'
                                        values: 'Home', 'Work', 'Other', 'Custom'
                                    BoxLayout:
                                        orientation: 'vertical'
                                        size_hint_x: 0.2
                                        spacing: dp(1)
                                        Button:
                                            text: '\u25B2'
                                            id: mode_name_chev_up_button_id
                                            font_name: 'build_fonts/Arial Unicode.ttf'
                                        Button:
                                            text: '\u25BC'
                                            id: mode_name_chev_down_button_id
                                            font_name: 'build_fonts/Arial Unicode.ttf'
                            ScaleInfo:
                                id: scale_logo_id
                                size_hint_y: 2
                                color: [0.9,0.9,0.9,1]




                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_x: 1
                            id: circle_of_fifths_box_id
                            # Border
                            canvas.before:
                                Color:
                                    rgba: 1, 1,1, .5
                                Line:
                                    width: root.line_width
                                    rectangle: self.x, self.y, self.width, self.height

                            EmptySpace:
                                text: 'New feature comming soon...\n(right here)'
                                id: new_feature_label_id
                                size_hint_y: 5
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                                color: [0.5, 0.5, 0.5, 1]
                            EmptySpace:
                                text: '\u262F'
                                size_hint_y: 6
                                font_name: 'build_fonts/Arial Unicode.ttf'
                                font_size: dp(400)
                                id: yinyang_logo_id
                                # halign: 'center'
                                # valign: 'middle'
                            EmptySpace:
                                size_hint_y: 6





<InfoSelectorView@BoxLayout>
    scale_information_tab_toggle: scale_information_tab_toggle
    help_tab_toggle: help_tab_toggle
    lessons_advanced_tab_toggle: lessons_advanced_tab_toggle
    credits_tab_toggle: credits_tab_toggle
    screen_manager_info_view: screen_manager_info_view
    scale_info_screen_id: scale_info_screen_id
    help_screen_id: help_screen_id
    lessons_advanced_screen_id: lessons_advanced_screen_id
    credits_screen_id: credits_screen_id
    credits_logo_id: credits_logo_id
    credits_label_id: credits_label_id

    line_width: 2

    label_lesson_beginner_title: label_lesson_beginner_title
    label_lesson_beginner_description: label_lesson_beginner_description
    label_lesson_advanced_title: label_lesson_advanced_title
    label_lesson_advanced_description: label_lesson_advanced_description

    all_lessons_id: all_lessons_id
    all_note_names_natual: all_note_names_natual
    all_note_names_accidental_sharp: all_note_names_accidental_sharp
    all_note_names_accidental_flat: all_note_names_accidental_flat
    minor_scale_note_names: minor_scale_note_names
    minor_scale_dots: minor_scale_dots
    minor_scale_degree: minor_scale_degree
    major_scale_note_names: major_scale_note_names
    major_scale_dots: major_scale_dots
    major_scale_degree: major_scale_degree
    arp_minor_1: arp_minor_1
    arp_minor_2: arp_minor_2
    arp_minor_3: arp_minor_3
    arp_minor_4: arp_minor_4
    arp_major_1: arp_major_1
    arp_major_2: arp_major_2
    arp_major_3: arp_major_3
    arp_major_4: arp_major_4
    arp7_minor_1: arp7_minor_1
    arp7_minor_2: arp7_minor_2
    arp7_minor_3: arp7_minor_3
    arp7_minor_4: arp7_minor_4
    arp7_major_1: arp7_major_1
    arp7_major_2: arp7_major_2
    arp7_major_3: arp7_major_3
    arp7_major_4: arp7_major_4
    alt3_full_1: alt3_full_1
    alt3_full_2: alt3_full_2
    alt3_position_1: alt3_position_1
    alt3_position_2: alt3_position_2
    alt3_position_3: alt3_position_3
    alt3_position_4: alt3_position_4
    alt3_position_5: alt3_position_5
    alt3_position_6: alt3_position_6
    alt3_position_7: alt3_position_7
    alt3_position_8: alt3_position_8
    alt3_position_9: alt3_position_9
    alt3_position_10: alt3_position_10
    alt3_position_11: alt3_position_11
    alt3_position_12: alt3_position_12
    alt3_position_13: alt3_position_13
    alt3_position_14: alt3_position_14
    alt3_maj_position_1: alt3_maj_position_1
    alt3_maj_position_2: alt3_maj_position_2
    alt3_maj_position_3: alt3_maj_position_3
    alt3_maj_position_4: alt3_maj_position_4
    alt3_maj_position_5: alt3_maj_position_5
    alt3_maj_position_6: alt3_maj_position_6
    alt3_maj_position_7: alt3_maj_position_7
    alt3_maj_position_8: alt3_maj_position_8
    alt3_maj_position_9: alt3_maj_position_9
    alt3_maj_position_10: alt3_maj_position_10
    alt3_maj_position_11: alt3_maj_position_11
    alt3_maj_position_12: alt3_maj_position_12
    alt3_maj_position_13: alt3_maj_position_13
    alt3_maj_position_14: alt3_maj_position_14
    scales_3_note_1: scales_3_note_1
    scales_3_note_2: scales_3_note_2
    scales_3_note_3: scales_3_note_3
    scales_3_note_4: scales_3_note_4
    scales_3_note_5: scales_3_note_5
    scales_3_note_6: scales_3_note_6
    scales_3_note_7: scales_3_note_7

    spacing_1 : 3
    spacing_2 : 3
    padding_1 : [0,0,0,0]
    padding_2 : [0,0,0,0]
    rez_scale : 1


    BoxLayout:

        orientation: 'vertical'

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.1
            padding: [0, 0, 0, dp(5)]
            # Label:
            #     text: 'Info'
            #     size_hint_x: .01
            #     font_size: dp(19)

            BoxLayout:

                ToggleButton:
                    text: 'Scale Info'
                    id: scale_information_tab_toggle
                    group: 'info_selection_tab_toggle'
                    font_size: dp(19)
                    state: 'down'
                    size_hint_x: 1

                ToggleButton:
                    text: 'Lesson Beg.'
                    id: help_tab_toggle
                    group: 'info_selection_tab_toggle'
                    font_size: dp(17)
                    size_hint_x: 1


                ToggleButton:
                    text: 'Lesson Adv.'
                    id: lessons_advanced_tab_toggle
                    group: 'info_selection_tab_toggle'
                    font_size: dp(17)
                    size_hint_x: 1


                ToggleButton:
                    text: 'Credits'
                    id: credits_tab_toggle
                    group: 'info_selection_tab_toggle'
                    font_size: dp(17)
                    size_hint_x: .7


            # EmptySpace:
            #     size_hint_x: .5
        BoxLayout:
            canvas.before:
                Color:
                    rgba: 1, 1,1, .5
                Line:
                    width: root.line_width
                    rectangle: self.x, self.y, self.width, self.height
            ScreenManager:
                id: screen_manager_info_view


                Screen:
                    name: 'scale_info_screen'

                    BoxLayout:
                        orientation: 'horizontal'

                        ScaleInfoScreen:
                            id: scale_info_screen_id



                Screen:
                    name: 'help_screen'
                    id: help_screen_id

                    BoxLayout:
                        orientation: 'vertical'
                        # spacing: 30

                        # Label:
                        #     text: '[size=40]Help[/size]\nClick notes on the fret for fitted scales.'
                        #     markup: True

                        Label:
                            text: 'Lesson Title'
                            id: label_lesson_beginner_title
                            size_hint_y: .2
                            padding: [dp(15),dp(15),dp(15),dp(5)]
                            text: '[size=70]None[/size]\nNo Lesson selected.\n\n'
                            markup: True
                            halign: 'center'
                            text_size: self.size
                            valign: 'top'
                        Label:
                            text: 'Lesson Description'
                            id: label_lesson_beginner_description
                            size_hint_y: .4
                            padding: [dp(15),dp(0),dp(15),dp(5)]
                            text: '[size=70]None[/size]\nNo Lesson selected.\n\n'
                            markup: True
                            halign: 'center'
                            text_size: self.size
                            valign: 'middle'
                            # valign: 'top'

                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(10)
                            # text_size: None
                            id: all_lessons_id
                            BoxLayout:
                                orientation: 'horizontal'
                                size_hint_y: 2
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Learn the notes'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: root.spacing_2

                                    BoxLayout:
                                        orientation: 'vertical'
                                        size_hint_x: 0.7
                                        spacing: dp(2)
                                        EmptySpace:
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: all_note_names_natual
                                            text: 'Natural'
                                            # padding: [dp(0),dp(5),dp(0),dp(5)]
                                            size_hint_y: 3
                                        EmptySpace:

                                    BoxLayout:
                                        orientation: 'vertical'
                                        spacing: dp(2)
                                        # padding: [dp(0),dp(2),dp(0),dp(2)]

                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: all_note_names_accidental_sharp
                                            text: 'Accidentals (#)'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: all_note_names_accidental_flat
                                            text: 'Accidentals (b)'

                            EmptySpace:
                                size_hint_y: 0.4

                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Major Scale'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: root.spacing_2
                                    padding: [dp(0),dp(2),dp(0),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: major_scale_dots
                                        text: 'Dot'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: major_scale_degree
                                        text: 'Degree'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: major_scale_note_names
                                        text: 'Name'



                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Minor Scale'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: root.spacing_2
                                    padding: [dp(0),dp(2),dp(0),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: minor_scale_dots
                                        text: 'Dot'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: minor_scale_degree
                                        text: 'Degree'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: minor_scale_note_names
                                        text: 'Name'

                            EmptySpace:
                                size_hint_y: 0.4

                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Arp Major'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: root.spacing_2
                                    padding: [dp(0),dp(2),dp(0),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_major_1
                                        text: '1'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_major_2
                                        text: '2'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_major_3
                                        text: '3'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_major_4
                                        text: '4'

                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Arp Minor'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: root.spacing_2
                                    padding: [dp(0),dp(2),dp(0),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_minor_1
                                        text: '1'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_minor_2
                                        text: '2'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_minor_3
                                        text: '3'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp_minor_4
                                        text: '4'

                            EmptySpace:
                                size_hint_y: 0.4

                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Arp Major 7'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: root.spacing_2
                                    padding: [dp(0),dp(2),dp(0),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_major_1
                                        text: '1'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_major_2
                                        text: '2'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_major_3
                                        text: '3'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_major_4
                                        text: '4'

                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Arp Minor 7'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: root.spacing_2
                                    padding: [dp(0),dp(2),dp(0),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_minor_1
                                        text: '1'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_minor_2
                                        text: '2'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_minor_3
                                        text: '3'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: arp7_minor_4
                                        text: '4'


                Screen:
                    name: 'lessons_advanced_screen'
                    id: lessons_advanced_screen_id

                    BoxLayout:
                        orientation: 'vertical'
                        # spacing: 30

                        # Label:
                        #     text: '[size=40]Help[/size]\nClick notes on the fret for fitted scales.'
                        #     markup: True

                        Label:
                            text: 'Lesson Title'
                            id: label_lesson_advanced_title
                            size_hint_y: .2
                            padding: [dp(15),dp(15),dp(15),dp(10)]
                            text: '[size=70]None[/size]\nNo Lesson selected.\n\n'
                            markup: True
                            halign: 'center'
                            text_size: self.size
                            valign: 'top'

                        Label:
                            text: 'Lesson Description'
                            id: label_lesson_advanced_description
                            size_hint_y: .3
                            padding: [dp(15),dp(0),dp(15),dp(10)]
                            text: '[size=70]None[/size]\nNo Lesson selected.\n\n'
                            markup: True
                            halign: 'center'
                            text_size: self.size
                            valign: 'top'

                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(10)
                            # text_size: None



                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: '3 note scales'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: dp(7)
                                    padding: [dp(0),dp(2),dp(0),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: scales_3_note_1
                                        text: '1'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: scales_3_note_2
                                        text: '2'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: scales_3_note_3
                                        text: '3'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: scales_3_note_4
                                        text: '4'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: scales_3_note_5
                                        text: '5'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: scales_3_note_6
                                        text: '6'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: scales_3_note_7
                                        text: '7'


                            EmptySpace:
                                size_hint_y: 0.4


                            BoxLayout:
                                orientation: 'horizontal'
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Alternating Thirds'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    spacing: dp(0)
                                    padding: [dp(20),dp(2),dp(20),dp(2)]
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: alt3_full_1
                                        text: 'Octave 1'
                                    ToggleButton:
                                        group: 'lesson_toggle'
                                        id: alt3_full_2
                                        text: 'Octave 2'

                            EmptySpace:
                                size_hint_y: 0.4

                            BoxLayout:
                                orientation: 'horizontal'
                                size_hint_y: 2
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Alternating Thirds\n(Major Scale)'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]

                                BoxLayout:
                                    orientation: 'vertical'
                                    BoxLayout:
                                        orientation: 'horizontal'
                                        spacing: dp(2)
                                        padding: [dp(0),dp(2),dp(0),dp(2)]
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_1
                                            text: '1'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_2
                                            text: '2'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_3
                                            text: '3'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_4
                                            text: '4'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_5
                                            text: '5'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_6
                                            text: '6'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_7
                                            text: '7'
                                    BoxLayout:
                                        orientation: 'horizontal'
                                        spacing: dp(2)
                                        padding: [dp(0),dp(2),dp(0),dp(2)]

                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_8
                                            text: '8'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_9
                                            text: '9'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_10
                                            text: '10'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_11
                                            text: '11'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_12
                                            text: '12'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_13
                                            text: '13'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_maj_position_14
                                            text: '14'
                                            # size_hint_x: 1.5



                            EmptySpace:
                                size_hint_y: 0.4


                            BoxLayout:
                                orientation: 'horizontal'
                                size_hint_y: 2
                                BoxLayout:
                                    orientation: 'horizontal'
                                    size_hint_x: .5
                                    Label:
                                        text: 'Alternating Thirds\n(Minor Scale)'
                                        text_size: self.size
                                        halign: 'right'
                                        valign: 'middle'
                                        padding: [0, 0, dp(10), 0]

                                BoxLayout:
                                    orientation: 'vertical'
                                    BoxLayout:
                                        orientation: 'horizontal'
                                        spacing: dp(2)
                                        padding: [dp(0),dp(2),dp(0),dp(2)]
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_1
                                            text: '1'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_2
                                            text: '2'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_3
                                            text: '3'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_4
                                            text: '4'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_5
                                            text: '5'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_6
                                            text: '6'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_7
                                            text: '7'
                                    BoxLayout:
                                        orientation: 'horizontal'
                                        spacing: dp(2)
                                        padding: [dp(0),dp(2),dp(0),dp(2)]

                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_8
                                            text: '8'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_9
                                            text: '9'
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_10
                                            text: '10'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_11
                                            text: '11'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_12
                                            text: '12'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_13
                                            text: '13'
                                            # size_hint_x: 1.5
                                        ToggleButton:
                                            group: 'lesson_toggle'
                                            id: alt3_position_14
                                            text: '14'
                                            # size_hint_x: 1.5







# all_note_names_natual
# all_note_names_accidental
# minor_scale_note_names
# minor_scale_dots
# minor_scale_degree
# major_scale_note_names
# major_scale_dots
# major_scale_degree
# arp_minor_1
# arp_minor_2
# arp_minor_3
# arp_minor_4
# arp_major_1
# arp_major_2
# arp_major_3
# arp_major_4
# arp7_minor_1
# arp7_minor_2
# arp7_minor_3
# arp7_minor_4
# arp7_major_1
# arp7_major_2
# arp7_major_3
# arp7_major_4
# alt3_full_1
# alt3_full_2
# alt3_position_1
# alt3_position_2
# alt3_position_3
# alt3_position_4
# alt3_position_5
# alt3_position_6
# alt3_position_7
# alt3_position_8
# alt3_position_9
# alt3_position_10
# alt3_position_11
# alt3_position_12
# scales_3_note_1
# scales_3_note_2
# scales_3_note_3
# scales_3_note_4
# scales_3_note_5
# scales_3_note_6
# scales_3_note_7





                Screen:
                    name: 'credits_screen'
                    id: credits_screen_id

                    BoxLayout:
                        orientation: 'vertical'

                        spacing: 30

                        Label:
                            text: '𓁈'
                            id: credits_logo_id
                            # text: '\u1360'
                            font_name: 'build_fonts/NotoSansEgyptianHieroglyphs-Regular.ttf'
                            font_size: dp(15)

                            size_hint_y: 1
                        Label:
                            id: credits_label_id
                            # text: '[size=70]Fretboard Computer[/size]\n  version alpha\n\n[size=40]Created by Andrew Bolt\n copyright 2024[/size]\n\nhttps://github.com/andrewbolt9000'
                            # text: f'[size={50*root.rez_scale}]Fretboard Computer[/size]\n [size={40*root.rez_scale}] version alpha[/size]\n\n[size={50*root.rez_scale}]Created by Andrew Bolt\n[size={40*root.rez_scale}] copyright 2024[/size][/size]\n\n[size={40*root.rez_scale}]https://github.com/andrewbolt9000[/size]'
                            text: f'Fretboard Computer\n   version alpha\nCreated by Andrew Bolt\n   copyright 2024\nhttps://github.com/andrewbolt9000'
                            # text: '[size=70]Fretboard Computer[/size]\n  version alpha\n\n[size=40]Created by Andrew Bolt\n copyright 2024[/size]\n\nhttps://github.com/andrewbolt9000'
                            # markup: True





<ScaleInfoScreen@BoxLayout>
    primary_name: primary_name
    mode_and_scale_type: mode_and_scale_type
    alternate_name: alternate_name
    scale_info_history: scale_info_history
    scale_info_history_label: scale_info_history_label
    piano_container_id: piano_container_id

    spacing_1 : 3
    spacing_2 : 3
    padding_1 : [0,0,0,0]
    padding_2 : [0,0,0,0]


    scale_info_details_box: scale_info_details_box
    BoxLayout:
        orientation: 'vertical'

        # Upper - Name
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 1.2

            padding: [0,dp(11),0,0]

            Label:
                text: 'A Minor'
                id: primary_name
                # padding: [0,400,0,0]
                font_size: dp(45)
                size_hint_y: 2.5
                # halign: 'right'
                halign: 'center'
                text_size: self.size
                # valign: 'bottom'
                valign: 'middle'
                # size_hint_y: None
                # text_size: self.width, None
                # height: self.texture_size[1]

            Label:
                text: 'aeolean mode of the diatonic scale'
                id: mode_and_scale_type
                markup: True
                font_size: dp(15)
                size_hint_y: .5
                # text_size: self.size
                # valign: 'top'
            Label:
                text: 'alt names'
                id: alternate_name
                font_size: dp(15)
                padding: root.padding_2
                markup: True
                size_hint_y: .9
                # text_size: self.size
                # valign: 'bottom'

        BoxLayout:
            orientation: 'vertical'
            id: piano_container_id
            size_hint_y: 0.7
            padding: [dp(30), 0,dp(30), 0]

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 3
            # spacing: root.spacing_2
            padding: [0,dp(13),0,0]
            # Lower - Details
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: 0.6
                id: scale_info_details_box
                ScaleInfoDetails:


            BoxLayout:
                orientation: 'horizontal'
                spacing: root.spacing_2
                label_text: 'default'
                content_text: 'default' * 4
                padding: [0,dp(13),dp(5),0]
                size_hint_y: 1.5

                Label:
                    text: 'History'
                    id: scale_info_history_label
                    size_hint_x: .5
                    halign: 'right'
                    text_size: self.size
                    valign: 'top'
                    color: (.7,.7,.7,1)
                    markup: True
                    # padding: root.padding_2

                Button:
                    id: scale_info_history
                    padding: [0, 0, dp(13), dp(0)]
                    text: 'Beloved by the egyptians, the phrygian mode dominated the early mediteranean civilizations.  For centuries peasants and kings agreed, Phrygian ROCKS!'
                    # valign: 'top'
                    halign: 'left'
                    valign: 'top'
                    font_size: dp(12)
                    text_size: self.width, self.height
                    markup: True
                    # text_size: self.width, None
                    size_hint_x: 1
                    size_hint_y: 1
                    # padding: [0,0,dp(40),0]
                    height: self.texture_size[1]
                    background_color: 0, 0, 0, 0

                    # Label:
                    #     text: root.content_text
                    #     halign: 'left'
                    #     text_size: self.size
                    #     valign: 'middle'

<ScaleInfoDetails@BoxLayout>
    orientation: 'horizontal'
    spacing: dp(15)
    label_text: 'default'
    content_text: 'default'
    label_font_size: dp(16)
    content_font_size: dp(16)
    content_button_id: content_button_id
    Label:
        text: root.label_text
        size_hint_x: .5
        halign: 'right'
        text_size: self.size
        valign: 'middle'
        color: (.7,.7,.7,1)
        font_size: root.label_font_size
    Button:
        text: root.content_text
        id: content_button_id
        background_normal: ''
        background_color: [0,0,0]
        halign: 'left'
        text_size: self.size
        markup: True
        valign: 'middle'
        font_size: root.content_font_size

<ScaleInfo@BoxLayout>
    scale_logo_font_size: dp(10)
    scale_logo_text: 'scale_logo_text'
    logo_button_id: logo_button_id
    Button:
        id: logo_button_id
        text: root.scale_logo_text
        padding: [dp(20),0,0,0]
        background_color: 0, 0, 0, 0
        font_size: root.scale_logo_font_size
        text_size: self.size
        valign: 'middle'
        # halign: 'right'
        halign: 'center'
        markup: True
        ## DEBUG
        # font_size: dp(10)
        font_name: 'build_fonts/NotoSansEgyptianHieroglyphs-Regular.ttf'


    # id: scale_logo_label_id


<DegreeExtensionScreen@BoxLayout>
    set_label: set_label
    octave_toggles: octave_toggles
    octave_1_toggle: octave_1_toggle
    octave_2_toggle: octave_2_toggle
    degree_set: degree_set
    degree_set_all: degree_set_all
    degree_set_none: degree_set_none
    degree_set_odd: degree_set_odd
    degree_set_even: degree_set_even
    quick_display_button: quick_display_button

    orientation: 'vertical'
        # spacing: 20

    BoxLayout:
        orientation: 'horizontal'

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: .5

            BoxLayout:
                size_hint_y: .9
                orientation: 'vertical'

                Label:
                    text: 'Set'
                    id: set_label
                    font_size: dp(19)
                    size_hint_y: .7
                    padding: [dp(0),dp(0),dp(0),dp(10),]

                BoxLayout:
                    orientation: 'horizontal'
                    EmptySpace:
                        size_hint_x: 1
                    ToggleButton:
                        id: quick_display_button
                        padding: [0,0,0,30]
                        # text: '\u13025'  # quick set display
                        text: '𓂀'  # quick set display
                        # text: '𓁹'  # quick set display
                        # padding: [dp(30), dp(0), dp(30), dp(0)]
                        size_hint_y: 1
                        # font_name: 'fontNewGardiner/NewGardinerSMP.ttf'
                        # font_name: 'fonts/NewGardiner/NewGardinerBMP.ttf'
                        font_name: 'build_fonts/NotoSansEgyptianHieroglyphs-Regular.ttf'
                        font_size: dp(30)

                        # font_name: 'build_fonts/Arial Unicode.ttf'
                    EmptySpace:
                        size_hint_x: 1

            BoxLayout:
                size_hint_y: .4
                orientation: 'horizontal'
                id: octave_toggles
                # spacing: root.spacing_2
                padding: [dp(10), dp(2.5), dp(10), dp(0.5)]

                ToggleButton:
                    text: 'Octave 1'
                    id: octave_1_toggle
                    group: 'octave_toggle'
                    state: 'down'
                    font_size: dp(12)
                ToggleButton:
                    text: 'Octave 2'
                    id: octave_2_toggle
                    group: 'octave_toggle'
                    font_size: dp(12)

        BoxLayout:
            orientation: 'vertical'
            GridLayout:
                cols: 7
                id: degree_set
                # spacing:
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.5
                spacing: 10
                padding: [0, 10, 0, 0]
                Button:
                    text: 'All'
                    id: degree_set_all
                    # size_hint_y: .5
                    font_size: dp(14)
                Button:
                    text: 'None'
                    id: degree_set_none
                    # size_hint_y: .5
                    font_size: dp(14)
                Button:
                    text: 'Odd'
                    id: degree_set_odd
                    # size_hint_y: .5
                    font_size: dp(14)
                Button:
                    text: 'Even'
                    id: degree_set_even
                    # size_hint_y: .5
                    font_size: dp(14)


<FilterSelectorView@BoxLayout>
    # swap_filter_order: swap_filter_order

    range_filter_tabs_label: range_filter_tabs_label
    ext_deg_filter_tabs_label: ext_deg_filter_tabs_label

    deg_ext_off_label: deg_ext_off_label
    deg_ext_off_sub_label: deg_ext_off_sub_label
    filter_min_nps_off_label: filter_min_nps_off_label
    filter_min_nps_off_sub_label: filter_min_nps_off_sub_label

    degree_tab_toggle: degree_tab_toggle
    extension_tab_toggle: extension_tab_toggle
    deg_ext_off_tab_toggle: deg_ext_off_tab_toggle

    screen_manager_deg_ext: screen_manager_deg_ext

    notes_per_string_1: notes_per_string_1
    notes_per_string_2: notes_per_string_2
    nps_starting_fret_spinner: nps_starting_fret_spinner
    nps_starting_fret_slider: nps_starting_fret_slider

    filter_degree_screen: filter_degree_screen
    filter_extension_screen: filter_extension_screen


    range_nps_tab_toggle: range_nps_tab_toggle
    range_min_fret_tab_toggle: range_min_fret_tab_toggle
    range_filters_off_tab_toggle: range_filters_off_tab_toggle
    screen_manager_range_filter: screen_manager_range_filter

    min_fret_spinner: min_fret_spinner
    min_fret_slider: min_fret_slider
    min_fret_label_id: min_fret_label_id
    nps_label_id: nps_label_id
    nps_starting_fret_label_id: nps_starting_fret_label_id

    sparator_arrow_label_id: sparator_arrow_label_id

    line_width: 2

    orientation: 'horizontal'

        # ScreenManager:
        #     id: sm
        #     Screen:
        #         name: 'Degree-Extension-Filters'
    spacing: dp(10)
    BoxLayout:
        orientation: 'horizontal'
        # size_hint_x: 1

        size_hint_x: 1.2

        BoxLayout:

            orientation: 'vertical'
            BoxLayout:

                # Border
                canvas.before:
                    Color:
                        rgba: 0.4,0.4,0.4, 1
                    Line:
                        width: root.line_width
                        # width: 2
                        points: self.x, self.y, self.x + self.width, self.y

                orientation: 'horizontal'
                size_hint_y: 0.25
                # padding: [0, 0, 0, dp(0)]
                Label:
                    text: 'Ext/Deg Filters'
                    id: ext_deg_filter_tabs_label
                    font_size: dp(20)
                    size_hint_x: 1.4
                    halign: 'left'
                    text_size: self.size


                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_x: 2

                    ToggleButton:
                        text: 'Degree'
                        id: degree_tab_toggle
                        group: 'deg_ext_tab_toggle'
                        font_size: dp(15)

                    ToggleButton:
                        text: 'Extension'
                        id: extension_tab_toggle
                        group: 'deg_ext_tab_toggle'
                        font_size: dp(15)
                        size_hint_x: 1.2

                    ToggleButton:
                        text: 'Off'
                        id: deg_ext_off_tab_toggle
                        group: 'deg_ext_tab_toggle'
                        font_size: dp(15)
                        size_hint_x: .5
                        state: 'down'


            BoxLayout:
                padding: [0, dp(10), 0, dp(0)]
                # # Border
                # canvas.before:
                #     Color:
                #         rgba: 1, 1,1, .5
                #     Line:
                #         width: 2
                #         rectangle: self.x, self.y, self.width, self.height
                ScreenManager:
                    id: screen_manager_deg_ext
                    Screen:
                        name: 'Degree'
                        DegreeExtensionScreen:
                            id: filter_degree_screen
                    Screen:
                        name: 'Extension-1'
                        DegreeExtensionScreen:
                            id: filter_extension_screen

                    Screen:
                        name: 'Off'
                        BoxLayout:
                            orientation: 'vertical'

                            EmptySpace:
                                size_hint_y: .1
                            EmptySpace:
                                size_hint_y: 1

                                id: deg_ext_off_label
                                text: '\u2623'
                                size_hint_x: 1
                                # width: dp(20)
                                font_size: dp(100)
                                font_name: 'build_fonts/Arial Unicode.ttf'

                            EmptySpace:
                                size_hint_y: .3
                                id: deg_ext_off_sub_label
                                text: 'Off'
                                font_size: dp(14)

                            # id: filter_extension_screen

    BoxLayout:
        size_hint_x: .08
        orientation: 'vertical'

        # # Border
        # canvas.before:
        #     Color:
        #         rgba: 1, 1,1, .2
        #     Line:
        #         width: 2
        #         rectangle: self.x, self.y, self.width, self.height

        # EmptySpace:
        #     size_hint_y: .5
        # Label:
        #     text: 'Swap\nfilter order:'
        # Switch:
        #     id: swap_filter_order
        # EmptySpace:
        #     size_hint_y: .5

        EmptySpace:
            text: '▶︎'
            id: sparator_arrow_label_id
            font_name: 'build_fonts/Arial Unicode.ttf'
            font_size: dp(30)
            color: (0.5,0.5,0.5,.5)







    BoxLayout:
        orientation: 'horizontal'
        size_hint_x: 1.2
        BoxLayout:
            orientation: 'vertical'
            BoxLayout:
                orientation: 'horizontal'
                id: range_filter_tabs_id
                # Border
                canvas.before:
                    Color:
                        # rgba: 1,1,1, 1
                        rgba: 0.4,0.4,0.4, 1
                    Line:
                        width: root.line_width
                        points: range_filter_tabs_id.x, range_filter_tabs_id.y, range_filter_tabs_id.x + range_filter_tabs_id.width, range_filter_tabs_id.y
                size_hint_y: 0.25
                Label:
                    text: 'Range Filter'
                    id: range_filter_tabs_label
                    font_size: dp(20)
                    size_hint_x: 1.2
                    halign: 'left'
                    text_size: self.size

                ToggleButton:
                            # (0.345, 0.345, 0.345, 1)
                            # background_color: 0.506, 0.173, 0.859, 1
                    # canvas.before:
                    #     Color:
                    #         rgba: (0.329, 0.635, 0.792, 1) if range_min_fret_tab_toggle.disabled else (0.345, 0.345, 0.345, 1)  # Disabled background color
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size
                    # disabled_color: (1,1,1, 1)

                    text: 'Minimum Fret'
                    id: range_min_fret_tab_toggle

                    group: 'range_filter_tab_toggle'
                    font_size: dp(15)
                    size_hint_x: 1.1

                ToggleButton:
                    text: 'Notes Per String'
                    id: range_nps_tab_toggle
                    size_hint_x: 1.25
                    # canvas.before:
                    #     Color:
                    #         rgba: (0.329, 0.635, 0.792, 1) if range_nps_tab_toggle.disabled else (0.345, 0.345, 0.345, 1)  # Disabled background color
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size
                    # disabled_color: (1,1,1, 1)

                    group: 'range_filter_tab_toggle'
                    font_size: dp(15)


                ToggleButton:
                    text: 'Off'
                    id: range_filters_off_tab_toggle
                    size_hint_x: 0.35
                    # canvas.before:
                    #     Color:
                    #         rgba: (0.329, 0.635, 0.792, 1) if range_filters_off_tab_toggle.disabled else (0.345, 0.345, 0.345, 1)  # Disabled background color
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size
                    # disabled_color: (1,1,1, 1)

                    group: 'range_filter_tab_toggle'
                    font_size: dp(15)
                    state: 'down'




            BoxLayout:
                # Border
                # canvas.before:
                #     Color:
                #         rgba: 1, 1,1, .5
                #     Line:
                #         width: 2
                #         rectangle: self.x, self.y, self.width, self.height
                padding: [0, dp(10), 0, dp(0)]

                ScreenManager:
                    id: screen_manager_range_filter

                    Screen:
                        name: 'Min Fret Range'
                        BoxLayout:
                            orientation: 'vertical'


                            # Label:
                            #     text: 'range ....'



                            BoxLayout:
                                orientation: 'horizontal'
                                spacing: dp(5)
                                size_hint_y: 1
                                BoxLayout:
                                    orientation: 'vertical'
                                    # EmptySpace:
                                    Label:
                                        text: 'Starting Fret'
                                        # padding: [0, dp(12)]
                                        id: min_fret_label_id
                                        halign: 'right'
                                        text_size: self.size
                                        valign: 'middle'
                                        # padding: [0, dp(15)]
                                        # width: dp(70)
                                    EmptySpace:
                                BoxLayout:
                                    orientation: 'vertical'
                                    BoxLayout:
                                        size_hint_y:0.8
                                        orientation: 'horizontal'
                                        EmptySpace:
                                        Spinner:
                                            # padding: [0, dp(50)]
                                            # width: dp(70 / 2)
                                            id: min_fret_spinner
                                            text: '3'
                                            values: '1', '2', '3', '4', '5'
                                            size_hint_x: 1.6
                                        EmptySpace:
                                    Slider:
                                        id: min_fret_slider
                                        min: 0
                                        max: 12
                                        step: 1






                    Screen:
                        name: 'Notes Per String'

                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_x: .8
                            BoxLayout:
                                orientation: 'horizontal'
                                spacing: dp(5)
                                Label:
                                    text: 'Notes per String'
                                    id: nps_label_id
                                    size_hint_x: 1.5
                                    halign: 'right'
                                    text_size: self.size
                                    valign: 'middle'
                                    padding: [0, dp(0), 0 , dp(15)]
                                BoxLayout:
                                    orientation: 'horizontal'
                                    padding: [0, dp(0), 0 , dp(15)]
                                    # spacing: dp(5)
                                    # size: self.size
                                    # size_hint_x: None
                                    width: dp(70)
                                    spacing: dp(2)
                                    Spinner:
                                        id: notes_per_string_1
                                        text: '3'
                                        values: '-', '1', '2', '3', '4', '5'
                                    Spinner:
                                        id: notes_per_string_2
                                        text: '-'
                                        values: '-', '1', '2', '3', '4', '5'

                            BoxLayout:
                                orientation: 'horizontal'
                                spacing: dp(5)
                                size_hint_y: 1.5
                                BoxLayout:
                                    orientation: 'vertical'
                                    size_hint_x: 1.5
                                    # EmptySpace:
                                    Label:
                                        text: 'Starting Fret'
                                        id: nps_starting_fret_label_id
                                        # padding: [0, dp(12)]
                                        halign: 'right'
                                        text_size: self.size
                                        valign: 'middle'
                                        # padding: [0, dp(15)]
                                        # width: dp(70)
                                    EmptySpace:
                                BoxLayout:
                                    orientation: 'vertical'
                                    # size_hint_y: 1.5
                                    BoxLayout:
                                        orientation: 'horizontal'
                                        EmptySpace:
                                        Spinner:
                                            # padding: [0, dp(50)]
                                            # width: dp(70 / 2)
                                            id: nps_starting_fret_spinner
                                            text: '3'
                                            values: '1', '2', '3', '4', '5'
                                            size_hint_x: 2
                                        EmptySpace:
                                    Slider:
                                        id: nps_starting_fret_slider
                                        size_hint_y: .8
                                        min: 0
                                        max: 12
                                        step: 1

                    Screen:
                        name: 'Off'
                        BoxLayout:
                            orientation: 'vertical'

                            # spacing: dp(5)

                            EmptySpace:
                                size_hint_y: .1
                                # text: 'Off'
                            EmptySpace:
                                size_hint_y: 1
                                id: filter_min_nps_off_label
                                # id: update_cache_button
                                text: '\u265E'
                                size_hint_x: 1
                                # width: dp(20)
                                font_size: dp(60)
                                font_name: 'build_fonts/Arial Unicode.ttf'

                            EmptySpace:
                                size_hint_y: .4
                                id: filter_min_nps_off_sub_label
                                text: 'Off'
                                font_size: dp(14)




<FilterDegreeSetButton@BoxLayout>
    btn: btn
    ToggleButton:
        id: btn
        text: 'none'
        state: 'down'





<TuningSelectorView@Button>
    text: 'TuningSelectorView'


<DisplaySelectorView@BoxLayout>

    note_display_type: note_display_type
    note_display_type_chev_up_button_id: note_display_type_chev_up_button_id
    note_display_type_chev_down_button_id: note_display_type_chev_down_button_id
    guitar_tuning_spinner: guitar_tuning_spinner
    increment_font_size_up_button_id: increment_font_size_up_button_id
    increment_font_size_down_button_id: increment_font_size_down_button_id

    quick_display_dot_toggle: quick_display_dot_toggle
    quick_display_name_toggle: quick_display_name_toggle
    quick_display_degree_toggle: quick_display_degree_toggle
    quick_display_extension_toggle: quick_display_extension_toggle
    quick_display_chord_degree_toggle: quick_display_chord_degree_toggle

    display_settings_label_id: display_settings_label_id
    note_display_type_label_id: note_display_type_label_id
    tuning_label_id: tuning_label_id

    line_width: 2

    orientation: 'vertical'
    size_hint_x: .5
    # spacing: dp(5)
    padding: [dp(5), dp(10), dp(5), dp(5)]
    # line_width: line_width
    # Border
    canvas.before:
        Color:
            rgba: 1, 1,1, .1
        Line:
            width: root.line_width
            rectangle: self.x, self.y, self.width, self.height

    # padding: [dp(10),dp(10),dp(10),dp(10),]



    BoxLayout:
        orientation: 'horizontal'
        spacing: dp(0)
        padding: [dp(0), dp(0), dp(8), dp(10)]
        size_hint_y: 1
        # EmptySpace:
        #     size_hint_x: 5

        # BoxLayout:
        #     orientation: ''
        Label:
            text: 'Display Settings'
            # halign: 'left'
            id: display_settings_label_id
            font_size: dp(23)
            padding: [dp(10), dp(5), dp(0), dp(0)]
            text_size: self.size
            halign: 'left'
            # valign: 'middle'
            valign: 'bottom'
            size_hint_x: 5
            # text_size: self.size



        # GridLayout:
        #     # orientation: 'horizontal'
        #     size_hint_x: 1

        #     cols: 3
        #     rows: 1
        #     # orientation: 'horizontal'
        #     spacing:dp(2)
        #     # GridNote:

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.7


            # EmptySpace:
            #     size_hint_y: 1

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 5
                padding: [dp(0), dp(0), dp(0), dp(5)]
                spacing:dp(2)

                # cols: 3
                # rows: 1
                # orientation: 'horizontal'
                # GridNote:

                BoxLayout:
                    size_hint_x: 1.2
                    orientation: 'vertical'
                    id : minus_box_layout_id

                    size_hint_x: 2
                    EmptySpace:
                        size_hint_y: 1
                    Button:
                        # Border
                        canvas.before:
                            Color:
                                rgb: 0.4,0.4,0.4
                            Line:
                                width: root.line_width
                                rectangle: self.x, self.y, self.width+dp(3), self.height
                        id: increment_font_size_down_button_id
                        text: 'A'
                        size_hint_y: 2
                        # width: dp(20)
                        font_size: dp(10)
                        font_name: 'build_fonts/Arial Unicode.ttf'
                        background_down: ''
                        background_color: [0,0,0]
                        color: [.6,.6,.6]

                Button:
                    # Border
                    canvas.before:
                        Color:
                            rgb: 0.4,0.4,0.4
                        Line:
                            width: root.line_width
                            rectangle: self.x, self.y, self.width, self.height

                    id: increment_font_size_up_button_id
                    text: 'A'
                    size_hint_x: 3
                    font_size: dp(32)
                    font_name: 'build_fonts/Arial Unicode.ttf'
                    background_down: ''
                    background_color: [0,0,0]
                    color: [.6,.6,.6]



            # EmptySpace:
            #     size_hint_y: 1


        # Button:
        #     # id: update_cache_button
        #     text: '\u2638'
        #     size_hint_x: 1
        #     # width: dp(20)
        #     font_size: dp(32)
        #     font_name: 'build_fonts/Arial Unicode.ttf'

        # Button:
        #     # id: update_cache_button
        #     text: '\u2623'
        #     size_hint_x: 1
        #     font_size: dp(32)
        #     # width: dp(20)
        #     font_name: 'build_fonts/Arial Unicode.ttf'

        # Button:
        #     id: update_cache_button
        #     text: '\u265E'
        #     size_hint_x: 1
        #     # width: dp(20)
        #     font_size: dp(26)
        #     font_name: 'build_fonts/Arial Unicode.ttf'

        # Button:
        #     id: debug_print_button
        #     text: '\u262C'
        #     size_hint_x: 1
        #     font_size: dp(34)
        #     font_name: 'build_fonts/Arial Unicode.ttf'


    # Button:
    #     id: highlight_filtered
    #     text: 'highlight_filtered'

    BoxLayout:
        orientation: 'horizontal'
        spacing: dp(10)
        size_hint_y: 1.6

        Label:
            # id: note_display_type
            text: 'Note Display Type:'
            id: note_display_type_label_id
            font_size: dp(17)
            halign: 'right'
            valign: 'middle'
            text_size: self.size
            markup: True
            size_hint_x: 0.6


        BoxLayout:
            orientation: 'vertical'
            spacing: dp(1)

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(1)
                size_hint_y: 0.6

                ToggleButton:
                    id: quick_display_dot_toggle
                    text: '●'
                    # text: '\u2638'
                    size_hint_x: 1
                    font_size: dp(20)
                    font_name: 'build_fonts/Arial Unicode.ttf'
                    group: 'quick_note_display_type'

                ToggleButton:
                    id: quick_display_name_toggle
                    text: 'N'
                    # text: '\u2623'
                    size_hint_x: 1
                    font_size: dp(14)
                    font_name: 'Jost'
                    group: 'quick_note_display_type'

                ToggleButton:
                    id: quick_display_degree_toggle
                    text: 'D'
                    # text: '\u265E'
                    size_hint_x: 1
                    font_size: dp(14)
                    font_name: 'Jost'
                    group: 'quick_note_display_type'

                ToggleButton:
                    id: quick_display_extension_toggle
                    text: 'E'
                    size_hint_x: 1
                    font_size: dp(14)
                    font_name: 'Jost'
                    group: 'quick_note_display_type'

                ToggleButton:
                    id: quick_display_chord_degree_toggle
                    text: 'CD'
                    size_hint_x: 1
                    font_size: dp(14)
                    font_name: 'Jost'
                    group: 'quick_note_display_type'

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(1)
                # size_hint_y: 0.6

                Spinner:
                    id: note_display_type
                    font_size: dp(18)
                    size_hint_x: 4.07
                BoxLayout:
                    orientation: 'vertical'
                    spacing: dp(1)
                    size_hint_x: 1

                    Button:
                        text: '\u25B2'
                        id: note_display_type_chev_up_button_id
                        font_name: 'build_fonts/Arial Unicode.ttf'
                    Button:
                        text: '\u25BC'
                        id: note_display_type_chev_down_button_id
                        font_name: 'build_fonts/Arial Unicode.ttf'


            # text: 'Home'
            # size_hint_y: 1.2
    # Button:
    #     id: note_display_sharp_flat
    #     text: 'note_display_sharp_flat'

    EmptySpace:
        size_hint_y: 0.1

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: .9
        spacing: dp(10)

        # EmptySpace:
        #     size_hint_y: 1

        Label:
            text: 'Tuning:'
            id: tuning_label_id
            # valign: 'bottom'
            # halign: 'center'
            font_size: dp(17)
            valign: 'middle'
            halign: 'right'
            text_size: self.size
            # font_size: dp(22)
            # font_size: dp(16)
            # size_hint_y: 1
            size_hint_x: 0.6


        Spinner:
            # size_hint: None, None
            # size: 100, 44
            # pos_hint: {'center': (.5, .5)}
            id: guitar_tuning_spinner
            text: '000'
            font_size: dp(18)
            values: 'aaaaa', 'b', 'c'
            size_hint_x: 1
            # size_hint_y: 1

        # EmptySpace:
        #     # size_hint_y: 3

<FretboardView@BoxLayout>
    # size_hint_x: 4
    spacing: dp(20)
    # guitar_tuning_spinner: guitar_tuning_spinner
    fretboard_wood: fretboard_wood
    fretboard_guide_top: fretboard_guide_top
    fretboard_guide_bottom: fretboard_guide_bottom

    orientation: 'horizontal'

    padding: [dp(0), dp(0), dp(30), dp(10)]

    line_width: 2

    # BoxLayout:
    #     orientation: 'vertical'
    #     size_hint_x: .1
    #     spacing: dp(5)

    #     # EmptySpace:
    #     #     size_hint_y: 1

    #     Label:
    #         text: 'Tuning:'
    #         valign: 'bottom'
    #         halign: 'center'
    #         text_size: self.size
    #         font_size: dp(22)
    #         # font_size: dp(16)
    #         size_hint_y: 1


    #     Spinner:
    #         # size_hint: None, None
    #         # size: 100, 44
    #         # pos_hint: {'center': (.5, .5)}
    #         id: guitar_tuning_spinner
    #         text: '000'
    #         font_size: dp(18)
    #         values: 'a', 'b', 'c'
    #         size_hint_y: 1

    #     EmptySpace:
    #         size_hint_y: 3


    BoxLayout:
        orientation: 'vertical'
        # spacing: 5
        size_hint_x: 1

        # EmptySpace:
        #     size_hint_y: .05
        FretboardGuideTop:
            id: fretboard_guide_top
            size_hint_y: .15


        FretboardWood:
            id: fretboard_wood
            size_hint_y: 1
        FretboardGuideBottom:
            id: fretboard_guide_bottom
            size_hint_y: .15
        # EmptySpace:
        #     size_hint_y: .1
        #     # size_hint_y: .1

    # EmptySpace:
    #     size_hint_x: .05
    # Rectangle:
        # background_color: 1,1,0
    # FretboardString:
    # FretboardString:
    # FretboardString:


<FretboardWood@BoxLayout>
    orientation: 'vertical'
    canvas.before:
        Color:
            # rgba: 1, .3, .8, 0
            rgba: 1, 1, 1, 0
            # rgba: 0, 0, 0, 0

        Rectangle:
            pos: self.pos
            size: self.size



<FretboardGuideTop@BoxLayout>
    orientation: 'vertical'
    canvas:
        Color:
            # rgba: 1, .3, .8, 0
            rgba: 0, 0, 0, 1
            # rgba: 0, 0, 0, 0
        # Rectangle:
        #     pos: self.pos
        #     size: self.size




<FretboardGuideBottom@BoxLayout>
    orientation: 'vertical'
    canvas:
        Color:
            # rgba: 1, .3, .8, 0
            rgba: 0, 0, 0, 1
            # rgba: 0, 0, 0, 0
        # Rectangle:
        #     pos: self.pos
        #     size: self.size



<FretboardString@BoxLayout>


    fretboard_string_headstock: fretboard_string_headstock
    fretboard_string_frets: fretboard_string_frets

    orientation: 'horizontal'


    FretboardStringHeadstock:
        id: fretboard_string_headstock
    FretboardStringFrets:
        id: fretboard_string_frets

    # canvas:
    #     Color:
    #         rgba: 0, .8, .2, .5
    #     Line:
    #         points: self.pos[0] + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
    #         # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
    #         # points: (self.x, self.y, self.x+100, self.y - self.height)
    #         width: 20
            # color: (.2, 1, 1, 1)
        # Rectangle:
        #     pos: self.pos
        #     size: self.size
        #     Color:



<FretboardStringHeadstock@RelativeLayout>
    button_id: button_id
    size_hint_x: 0.03
    # size_hint_x: 0.05
    # canvas
    Button:
        text: 'a'
        font_size: dp(10)
        id: button_id
        color:  .7,.7,.7,1
        background_color: 0, 0, 0, 0
        # font_name: root.FONT_NAME


<FretboardStringFrets@RelativeLayout>
    frets_box_layout: frets_box_layout
    # line_width: 2
    # guitar_strings
    canvas.before:
        Color:
            # rgba: 1, .3, .8, .5
            # rgba: 1, 1, 1, 0.2
            rgba: 0.2, 0.2, 0.2, 1

        Rectangle:
            # pos: self.pos
            size: self.size
            # size: (self.size[0] - 10, self.size[1] - 10)

    RelativeLayout:
        canvas.before:
            Color:
                # rgba: 0, .8, .2, .3
                rgba: 0,0,0, .02
            Line:
                points: self.pos[0] - 30, self.y + self.height / 2, self.x + self.width - 3, self.y + self.height / 2
                # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
                # points: (self.x, self.y, self.x+100, self.y - self.height)
                width: 6

    RelativeLayout:
        canvas.before:
            Color:
                # rgba: 0, .8, .2, .3
                # rgba: 0,0,0, 1
                rgba: 0,0,0, .02
            Line:
                points: self.pos[0] - 30, self.y + self.height / 2, self.x + self.width - 3, self.y + self.height / 2
                # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
                # points: (self.x, self.y, self.x+100, self.y - self.height)
                width: 2
                # width: 2 + (3.5 * self.string_number)

    BoxLayout:
        id: frets_box_layout
        orientation: 'horizontal'



<FretboardStringGuide@BoxLayout>


    fretboard_string_headstock: fretboard_string_headstock
    fretboard_string_frets: fretboard_string_frets

    orientation: 'horizontal'


    FretboardStringHeadstock:
        id: fretboard_string_headstock
    FretboardStringFretsGuide:
        id: fretboard_string_frets


<FretboardStringFretsGuide@RelativeLayout>
    frets_box_layout: frets_box_layout

    canvas:
        Color:
            # rgba: 1, .3, .8, .5
            rgba: 1, 1, 1, .4

        # Rectangle:
        #     # pos: self.pos
        #     size: self.size
        #     # size: (self.size[0] - 10, self.size[1] - 10)

    # RelativeLayout:
    #     canvas:
    #         Color:
    #             # rgba: 0, .8, .2, .3
    #             rgba: 0,0,0, .05
    #         Line:
    #             points: self.pos[0] - 30, self.y + self.height / 2, self.x + self.width - 3, self.y + self.height / 2
    #             # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
    #             # points: (self.x, self.y, self.x+100, self.y - self.height)
    #             width: 5

    # RelativeLayout:
    #     canvas:
    #         Color:
    #             # rgba: 0, .8, .2, .3
    #             rgba: 0,0,0, .05
    #         Line:
    #             points: self.pos[0] - 30, self.y + self.height / 2, self.x + self.width - 3, self.y + self.height / 2
    #             # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
    #             # points: (self.x, self.y, self.x+100, self.y - self.height)
    #             width: 2

    BoxLayout:
        id: frets_box_layout





# <FBButtonFretLine@FloatLayout>
#     canvas:
#         Color:
#             rgba: 1,1,1, .3
#             # rgba: 0, .8, .2, .3
#         # Line:
#         #     points: self.pos[0]  , self.y, self.x +20, self.y + self.height
#         #     # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
#         #     # points: (self.x, self.y, self.x+100, self.y - self.height)
#         #     width: 5

#         # Line:
#         #     width: 10 if parent.fret_text == 0 else 2
#         #     ellipse: (self.x - 10, self.y, self.width, self.height)



<FBButton@BoxLayout>:
    orientation: 'horizontal'
    size_hint_x: 1


    background_color: 1,0,0,0.1
    button_label: button_label
    # rect_id: rect_id
    canvas:
        Color:
            rgba: .9, .9, .9, 0.3

        Rectangle:
            # id: rect_id
            # width: 2
            # points: (self.x, self.y, self.width, self.height)
            # points: (self.x, self.y, self.width, self.height)
            pos: (self.x + self.width - 5, self.y - 0)
            size: (self.fret_thickness * 2 , self.height)
            # width: 10 if parent.fret_text == 0 else 2


        Rectangle:
            # id: rect_id
            # width: 2
            # points: (self.x, self.y, self.width, self.height)
            # points: (self.x, self.y, self.width, self.height)
            pos: (self.x + self.width - 8, self.y - 0)
            size: (self.fret_thickness * 3 , self.height)
            # width: 10 if parent.fret_text == 0 else 2

        Color:
            rgba: 0,0,0, .7

        Rectangle:
            pos: (self.x + self.width - 2, self.y - 0)
            size: (self.fret_thickness * 1 , self.height + dp(0))



        # Line:
        #     points: self.pos[0]  , self.y, self.x +20, self.y + self.height
        #     # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
        #     # points: (self.x, self.y, self.x+100, self.y - self.height)
        #     width: 5

        # Color:
        #     rgba: .9, .9, .9, 0.1 if self.is_music_root else 0
        # Ellipse:
        #     pos: (self.center_x - min(self.width, self.height)/2, self.y)
        #     size: (min(self.width, self.height), min(self.width, self.height))
            # size: (self.width, self.height)



    Button:

        # background_color: 1,1,0,0.3
        background_color: 0, 0, 0, 0
        id: button_label
        # font_size: dp(19)
        font_size: dp(19)
        # on_press: self.background_color = (0, 1, 0, 1)
        # on_release: self.background_color = (1, 0, 0, 1)



        # canvas:
        #     Color:
        #         rgba: .9, 0, .9, 0.5
        #     # Line:
        #     #     points: self.pos[0]  , self.y, self.x +20, self.y + self.height
        #     #     # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
        #     #     # points: (self.x, self.y, self.x+100, self.y - self.height)
        #     #     width: 5

        #     Rectangle:
        #         # id: rect_id
        #         # width: 2
        #         # points: (self.x, self.y, self.width, self.height)
        #         # points: (self.x, self.y, self.width, self.height)
        #         pos: (self.x + self.width, self.y - 5)
        #         size: (root.fret_thickness*2, self.height)
        #         # width: 10 if parent.fret_text == 0 else 2


<FBGuideButton@BoxLayout>:
    orientation: 'horizontal'

    size_hint_x: 1

    background_color: 1,0,0,0.1
    button_label: button_label
    # rect_id: rect_id
    canvas:
        Color:
            rgba: .9, .9, 0, 0.1
        # Line:
        #     points: self.pos[0]  , self.y, self.x +20, self.y + self.height
        #     # points: self.x + 30, self.y + self.height / 2, self.x + self.width - 30, self.y + self.height / 2
        #     # points: (self.x, self.y, self.x+100, self.y - self.height)
        #     width: 5

        # Rectangle:
        #     # id: rect_id
        #     # width: 2
        #     pos: (self.x + self.width - 5, self.y - 5)
        #     size: (self.fret_thickness , self.height)
        #     # size: self.size
        #     # width: 10 if parent.fret_text == 0 else 2

        # Rectangle:
        #     # id: rect_id
        #     # width: 2
        #     # points: (self.x, self.y, self.width, self.height)
        #     # points: (self.x, self.y, self.width, self.height)
        #     pos: (self.x + self.width - 5, self.y - 5)
        #     size: (self.fret_thickness , self.height)
        #     # width: 10 if parent.fret_text == 0 else 2


        # Rectangle:
        #     # id: rect_id
        #     # width: 2
        #     # points: (self.x, self.y, self.width, self.height)
        #     # points: (self.x, self.y, self.width, self.height)
        #     pos: (self.x + self.width - 8, self.y - 5)
        #     size: (self.fret_thickness * 2 , self.height)
        #     # width: 10 if parent.fret_text == 0 else 2


        # Color:
        #     rgba: .9, .9, .9, 0.1 if self.is_music_root else 0
        # Ellipse:
        #     pos: (self.center_x - min(self.width, self.height)/2, self.y)
        #     size: (min(self.width, self.height), min(self.width, self.height))
            # size: (self.width, self.height)


        Color:
            rgba: 0,1,1, 0
            group: 'rect_color_group'


        Rectangle:
            group: 'rect_group'
            pos: (self.x + self.width - 2, self.y - 0)
            size: (self.fret_thickness * 1 , self.height + dp(0))



    Button:
        # background_color: 1,1,0,0.3
        background_color: 0, 0, 0, 0
        id: button_label
        font_size: dp(11)
        # font_name: 'Monaco.ttf'
        font_name: 'build_fonts/Arial Unicode.ttf'
        # on_press: self.background_color = (0, 1, 0, 1)
        # on_release: self.background_color = (1, 0, 0, 1)









<RootWidget>
    # b1: btn_a
    # b2: btn_b
    # l1: spec_lab

    # key_view: key_view
    scale_selector_view: scale_selector_view
    info_selector_view: info_selector_view

    filter_selector_view: filter_selector_view
    display_selector_view: display_selector_view
    fretboard_view: fretboard_view
    main_box_layout: main_box_layout
    bl_1_0: bl_1_0
    bl_1_1: bl_1_1

    canvas:
        # Rectangle:
        #     pos: 0,0
        #     size: self.width, self.height



    BoxLayout:
        id: main_box_layout
        orientation: 'vertical'
        spacing: dp(10)
        padding: [dp(20),dp(20),dp(10),dp(10)]

        # Essential
        size: root.width, root.height

        # # Header
        # BoxLayout:
        #     # orientation: 'horizontal'
        #     orientation: 'vertical'
        #     size_hint_y: .6
        #     # height: 100
        #     Label:
        #         text: 'Fretboard Computer'
        #         # halign: 'left'
        #         halign: 'right'
        #         valign: 'middle'
        #         text_size: self.size
        #         font_size: dp(31)
        #         # width: dp(100)
        #         # width: 100
        #         # width: 100
        #         # size_hint_y: .7
        #     # Label:
        #     #     text: f'ALPHA v0.1'
        #     #     font_name: 'Monaco.ttf'
        #     #     # index: -4
        #     #     halign: 'left'
        #     #     # width: 100
        #     #     text_size: self.size
        #     #     # text_size: self.size
        #     #     font_size: dp(11)
        #     #     size_hint_y: .3



        BoxLayout:
            # Upper row
            id: bl_1_0
            orientation: 'horizontal'
            size_hint_y: 5
            spacing: dp(20)

            # KeyView:
            #     id: key_view
            ScaleSelectorView:
                id: scale_selector_view
                size_hint_x: 2
            InfoSelectorView:
                id: info_selector_view
                size_hint_x: 1
                text: 'info view'


        BoxLayout:
            id: bl_1_1
            orientation: 'horizontal'
            size_hint_y: 2.8
            padding: [0,dp(10),0,0]
            # Lower row

            FretboardView:
                id: fretboard_view


        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 1.6
            spacing: dp(20)
            FilterSelectorView:
                id: filter_selector_view
                size_hint_x: 2.3
            DisplaySelectorView:
                size_hint_x: 1
                id: display_selector_view

        # EmptySpace:
        #     size_hint_y: .2

