title: Freboard Calculator
description: Official website for Fretboard Calculator
baseurl: "" # leave blank if root
url: "https://andrewbolt9000.github.io" # or your custom domain




theme: minima

# Optional: if you want GitHub-style Pages config
plugins:
  - jekyll-feed
  - jekyll-seo-tag



header_pages:
  - index.md
  - support.md
  - about.md



defaults:
  -
    scope:
      path: ""
    values:
      css: /assets/css/custom.css

