title: Fretboard Calculator
description: Official website for Fretboard Calculator
baseurl: /fretboardcalculator # repo name
url: "https://andrewbolt9000.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - support.md
  - about.md
